name: Validate Notebooks

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "notebooks/**/*.ipynb"
      - ".github/workflows/validate-notebooks.yml"
  push:
    branches: [ main ]
    paths:
      - "notebooks/**/*.ipynb"
      - ".github/workflows/validate-notebooks.yml"

permissions:
  contents: read

jobs:
  validate_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Set the notebooks to validate, wildcards are allowed
        notebooks_to_validate: ["notebooks/**/*.ipynb"]
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip

      - name: Install Testing Tools
        run: |
          pip install pytest nbformat nbstripout ipython ipykernel jupyter-client
          ipython kernel install --name "python3" --user

      - name: Run Formatting Tests
        run: make format-notebooks-check

      - name: Validate Notebook Parameters
        run: make test-notebook-parameters
